version: '3'

services:
  todotests:
    image: todotests
    restart: always
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
    networks:
      - todo-app
  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - todo-app
  todoback:
    image: todobackend
    restart: always
    ports:
    - 3001:3001
    networks:
      - todo-app

networks:
  todo-app:
